// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_qJ0oIdtIgJCkj7D5zYu8lhhZdvPH0E',
    appId: '1:661807557113:web:1d589438523f74fcf87528',
    messagingSenderId: '661807557113',
    projectId: 'climb-8cfa9',
    authDomain: 'climb-8cfa9.firebaseapp.com',
    storageBucket: 'climb-8cfa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_jeWwL4NXwxRdVZ8_44Sjbfv4Rfjz2E',
    appId: '1:661807557113:android:b444d2498fe11eb4f87528',
    messagingSenderId: '661807557113',
    projectId: 'climb-8cfa9',
    storageBucket: 'climb-8cfa9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg_qJ0oIdtIgJCkj7D5zYu8lhhZdvPH0E',
    appId: '1:661807557113:web:86f4e5ae0bce022df87528',
    messagingSenderId: '661807557113',
    projectId: 'climb-8cfa9',
    authDomain: 'climb-8cfa9.firebaseapp.com',
    storageBucket: 'climb-8cfa9.appspot.com',
  );
}
